/**
 * Slovak spell-checking service — browser-side Hunspell via ``nspell``
 * bundled with the LibreOffice Slovak dictionary (``dictionary-sk``).
 *
 * Ships with the NEX Studio frontend so every text editor in the app
 * understands Slovak regardless of the user's browser language
 * settings. Also intended for reuse in projects generated by NEX
 * Studio — the API is browser-agnostic and framework-free so a later
 * extraction into an ICC-shared package is straightforward.
 *
 * Dictionary files are loaded lazily on the first :func:`getSpellchecker`
 * call and cached for the rest of the session. The ~1 MB payload is
 * therefore only fetched when the user opens an editor, never on
 * first paint of the dashboard or project picker.
 *
 * Personal "ignore" words are stored under the ``nex-spellchecker-ignore``
 * localStorage key so user-taught exceptions survive reloads and
 * browser restarts, the same way :mod:`activeContextStore` persists.
 */

import nspell from "nspell";

// The Slovak Hunspell files (~100 kB aff + ~3.5 MB dic) are copied from
// ``node_modules/dictionary-sk`` into ``/dictionaries/sk/`` at build time
// by ``vite-plugin-static-copy`` (see ``vite.config.ts``). Fetching them
// via plain HTTP avoids the restrictive ``exports`` map in
// ``dictionary-sk``'s package.json that blocks Vite's ``?url`` subpath
// imports.
const AFF_URL = "/dictionaries/sk/index.aff";
const DIC_URL = "/dictionaries/sk/index.dic";

type Spell = ReturnType<typeof nspell>;

let spellPromise: Promise<Spell> | null = null;

async function loadSpellchecker(): Promise<Spell> {
  const [affResp, dicResp] = await Promise.all([fetch(AFF_URL), fetch(DIC_URL)]);
  if (!affResp.ok || !dicResp.ok) {
    throw new Error(
      `Spellchecker dictionary fetch failed: aff=${affResp.status} dic=${dicResp.status}. ` +
        `Expected ${AFF_URL} and ${DIC_URL} to be served by the frontend (check vite-plugin-static-copy).`,
    );
  }
  // Hunspell dictionaries are UTF-8 text; ``nspell`` accepts string input
  // which avoids the Node ``Buffer`` dependency in the browser bundle.
  const [affText, dicText] = await Promise.all([affResp.text(), dicResp.text()]);
  return nspell(affText, dicText);
}

/**
 * Return the lazily-initialised Slovak spellchecker. Safe to call
 * concurrently — the underlying dictionary load is memoised on the
 * first invocation and every subsequent caller awaits the same
 * promise.
 */
export function getSpellchecker(): Promise<Spell> {
  if (!spellPromise) spellPromise = loadSpellchecker();
  return spellPromise;
}

// ─── Personal "ignore" dictionary ───────────────────────────────────────────

const IGNORE_KEY = "nex-spellchecker-ignore";

function readIgnored(): Set<string> {
  if (typeof window === "undefined") return new Set();
  try {
    const raw = window.localStorage.getItem(IGNORE_KEY);
    if (!raw) return new Set();
    const arr = JSON.parse(raw);
    return Array.isArray(arr) ? new Set(arr.map(String)) : new Set();
  } catch {
    return new Set();
  }
}

function writeIgnored(ignored: Set<string>): void {
  if (typeof window === "undefined") return;
  try {
    window.localStorage.setItem(IGNORE_KEY, JSON.stringify([...ignored]));
  } catch {
    // Storage full / disabled — silent no-op, next check just won't skip.
  }
}

/** Return the set of words the user has added to their personal dictionary. */
export function getIgnoredWords(): Set<string> {
  return readIgnored();
}

/** Add a word to the personal dictionary (stored lowercased for case-insensitive match). */
export function addIgnoredWord(word: string): void {
  const ignored = readIgnored();
  ignored.add(word.toLowerCase());
  writeIgnored(ignored);
}
