"""Add ui_design_port column to projects.

Fourth port slot per project — hosts the mockup preview surface
generated by the pipeline's Step 2B UI Design phase. Per ICC
DECISIONS.md D-020 (Port Registry v2), each project reserves a
10-port block with layout +0 backend, +1 frontend, +2 db, **+3
ui-design**, +4..+9 reserve.

Nullable to match the existing port columns — a project that does
not serve a mockup preview leaves this NULL.

Revision ID: 028
Revises: 027
Create Date: 2026-04-23
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = "028"
down_revision: Union[str, None] = "027"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "projects",
        sa.Column("ui_design_port", sa.Integer(), nullable=True),
    )


def downgrade() -> None:
    op.drop_column("projects", "ui_design_port")
