"""Shared helpers for UAT CLI nástroje (F-003).

Per F-003 §3-§4 spec + Sub-round 4 O-DS-2 (Python + rich) + O-003-2 (forever
snapshot retention).

v0.9.0 Phase 2 (CR-2): the per-project provisioning logic (source-compose
detection, synthetic-secret/.env synthesis, redeploy preservation, compose
rendering) MOVED to the importable :mod:`backend.services.uat_provisioner` so
the engine can provision in-process. This module now keeps only the shared
**ops** helpers used by the manual CLIs (uat-deploy / uat-teardown /
uat-snapshot / uat-status).

Public API:
- Slug validation: validate_slug()
- Path utilities: uat_dir, snapshots_dir, project_dir, uat_compose_path,
  uat_env_path, read_uat_env, nginx_config_path, local_nginx_config_path
- Port allocation: allocate_port, release_port, get_allocated_port
- Snapshot filenames: snapshot_filename
- Subprocess wrappers: docker_compose, docker_exec, wait_healthy, git_describe
- Template rendering: render_template
- Rich UI: console, confirm, status_table, print_url

State files:
- PORT_STATE_FILE: /opt/projects/nex-studio/.uat-ports.json (gitignored)
- TEMPLATES_DIR: /opt/projects/nex-studio/templates
"""

from __future__ import annotations

import json
import os
import re
import subprocess
import sys
import time
import urllib.error
import urllib.request
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import jinja2
from rich.console import Console
from rich.table import Table

NEX_STUDIO_ROOT = Path(__file__).resolve().parents[1]
PORT_STATE_FILE = NEX_STUDIO_ROOT / ".uat-ports.json"
TEMPLATES_DIR = NEX_STUDIO_ROOT / "templates"

DEFAULT_PORT_RANGE_START = 19500
DEFAULT_PORT_RANGE_END = 19599

SLUG_PATTERN = re.compile(r"^[a-z0-9][a-z0-9-]*$")

console = Console()
error_console = Console(stderr=True)


# ---------- Slug validation ----------


def validate_slug(slug: str) -> None:
    """Raise ValueError if slug is not a valid UAT slug.

    Rules:
    - Non-empty
    - Lowercase ASCII letters, digits, hyphens
    - Must start with letter or digit (no leading hyphen, dot, slash)
    """
    if not slug:
        raise ValueError("slug must not be empty")
    if slug != slug.lower():
        raise ValueError(f"slug must be lowercase: {slug!r}")
    if "/" in slug:
        raise ValueError(f"slug contains slash (invalid char): {slug!r}")
    if not SLUG_PATTERN.match(slug):
        raise ValueError(f"slug invalid char (allowed: a-z, 0-9, hyphen, no leading hyphen): {slug!r}")


# ---------- Path utilities ----------


def uat_dir(slug: str) -> Path:
    validate_slug(slug)
    return Path("/opt/uat") / slug


def snapshots_dir(slug: str) -> Path:
    return uat_dir(slug) / "snapshots"


def project_dir(project: str) -> Path:
    validate_slug(project)
    return Path("/opt/projects") / project


def uat_compose_path(slug: str) -> Path:
    return uat_dir(slug) / "docker-compose.yml"


def uat_env_path(slug: str) -> Path:
    """UAT .env file path: /opt/uat/<slug>/.env."""
    return uat_dir(slug) / ".env"


def read_uat_env(slug: str) -> dict[str, str]:
    """Parse /opt/uat/<slug>/.env into a dict (CR-025 single source of truth).

    Used by ``uat-snapshot.py`` and ``uat-teardown.py`` to recover the detected
    POSTGRES_USER + POSTGRES_DB (per CR-022) without re-running detection from
    the source compose — uat-deploy already wrote them here at deploy time.

    Ignores blank lines + ``#`` comments. Values are returned as raw strings
    (no quote stripping, no ``${VAR}`` expansion — UAT .env is generated by
    uat-deploy without those constructs).

    Returns an empty dict if the file does not exist (caller decides fallback
    behavior, typically erroring out before calling docker exec).
    """
    path = uat_env_path(slug)
    if not path.is_file():
        return {}
    out: dict[str, str] = {}
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        if "=" not in line:
            continue
        key, _, value = line.partition("=")
        out[key.strip()] = value
    return out


def nginx_config_path(slug: str) -> Path:
    """Final NGINX sites-available path (root-owned — sudo required to write).

    Legacy (pre-Traefik) UATs: used by ``uat-teardown.py`` to clean up an old
    vhost. The provisioner no longer renders nginx (Traefik replaces it).
    """
    validate_slug(slug)
    return Path("/etc/nginx/sites-available") / f"uat-{slug}.conf"


def local_nginx_config_path(slug: str) -> Path:
    """User-writable nginx config path: /opt/uat/<slug>/nginx-uat-vhost.conf.

    Legacy (pre-Traefik) UATs only — kept so ``uat-teardown.py`` can remove a
    leftover vhost from a UAT provisioned before the Traefik migration.
    """
    return uat_dir(slug) / "nginx-uat-vhost.conf"


# ---------- Port allocation ----------


def _load_port_state() -> dict[str, int]:
    if not PORT_STATE_FILE.exists():
        return {}
    try:
        return json.loads(PORT_STATE_FILE.read_text(encoding="utf-8"))
    except json.JSONDecodeError:
        return {}


def _save_port_state(state: dict[str, int]) -> None:
    PORT_STATE_FILE.parent.mkdir(parents=True, exist_ok=True)
    PORT_STATE_FILE.write_text(json.dumps(state, indent=2, sort_keys=True), encoding="utf-8")


def allocate_port(
    slug: str,
    *,
    range_start: int = DEFAULT_PORT_RANGE_START,
    range_end: int = DEFAULT_PORT_RANGE_END,
) -> int:
    """Allocate next free port in range for slug. Idempotent: existing slug returns same port."""
    validate_slug(slug)
    state = _load_port_state()

    if slug in state and range_start <= state[slug] <= range_end:
        return state[slug]

    used_ports = set(state.values())
    for port in range(range_start, range_end + 1):
        if port not in used_ports:
            state[slug] = port
            _save_port_state(state)
            return port

    raise RuntimeError(f"port range {range_start}-{range_end} exhausted (no free port for {slug!r})")


def release_port(slug: str) -> None:
    """Remove slug from allocation state. No-op if not allocated."""
    state = _load_port_state()
    if slug in state:
        del state[slug]
        _save_port_state(state)


def get_allocated_port(slug: str) -> int | None:
    """Return allocated port for slug, or None if not allocated."""
    return _load_port_state().get(slug)


# ---------- Snapshot filename ----------


def snapshot_filename(
    version: str,
    *,
    reason: str | None = None,
    teardown: bool = False,
) -> str:
    """Build snapshot filename per F-003 §8 convention.

    Examples:
        v0.1.0-2026-06-15.sql.gz
        v0.1.0-2026-06-15-before-experimental.sql.gz
        v0.1.0-2026-06-15-teardown.sql.gz
    """
    date = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    parts = [version, date]
    if reason:
        parts.append(reason)
    if teardown:
        parts.append("teardown")
    return "-".join(parts) + ".sql.gz"


# ---------- Subprocess wrappers ----------


def docker_compose(
    args: list[str],
    *,
    cwd: Path,
    capture: bool = False,
    env: dict[str, str] | None = None,
) -> subprocess.CompletedProcess:
    """Run `docker compose <args>` in given cwd. Raises CalledProcessError on non-zero.

    ``env`` (if given) is overlaid on the inherited environment — used to pass build-time vars like
    ``APP_VERSION`` to ``docker compose build`` so the compose ``${APP_VERSION}`` substitution
    resolves (CR-NS-062).
    """
    cmd = ["docker", "compose", *args]
    return subprocess.run(
        cmd,
        cwd=cwd,
        check=True,
        capture_output=capture,
        text=True,
        env={**os.environ, **env} if env else None,
    )


def git_describe(cwd: Path) -> str:
    """`git describe --tags --always` of the repo at ``cwd``; ``"0.0.0-dev"`` on any failure.

    The single source of the baked version for both the FE host-build (CR-NS-060) and the backend
    image build-arg (CR-NS-062), so FE + BE report the same version.
    """
    try:
        result = subprocess.run(
            ["git", "describe", "--tags", "--always"],
            cwd=cwd,
            check=True,
            capture_output=True,
            text=True,
        )
    except (subprocess.CalledProcessError, FileNotFoundError):
        return "0.0.0-dev"
    return result.stdout.strip() or "0.0.0-dev"


def docker_exec(
    container: str,
    command: list[str],
    *,
    capture: bool = False,
) -> subprocess.CompletedProcess:
    """Run `docker exec <container> <command>`. Raises CalledProcessError on non-zero."""
    cmd = ["docker", "exec", container, *command]
    return subprocess.run(cmd, check=True, capture_output=capture, text=True)


def wait_healthy(
    url: str,
    *,
    timeout: int = 120,
    interval: float = 5.0,
) -> bool:
    """Poll url until 2xx response or timeout. Returns True if healthy, False if timeout."""
    deadline = time.monotonic() + timeout
    while time.monotonic() < deadline:
        try:
            with urllib.request.urlopen(url, timeout=interval) as resp:
                if 200 <= resp.status < 300:
                    return True
        except Exception:  # noqa: BLE001 — any network/HTTP error means not-yet-healthy
            pass
        time.sleep(interval)
    return False


# ---------- Template rendering ----------


def render_template(template_name: str, context: dict[str, str]) -> str:
    """Render Jinja2 template from TEMPLATES_DIR with given context.

    template_name is relative to TEMPLATES_DIR (e.g. "uat/test.conf"). Generic helper used by the
    UAT CLIs; the compose template is rendered by :mod:`backend.services.uat_provisioner`.
    """
    env = jinja2.Environment(
        loader=jinja2.FileSystemLoader(str(TEMPLATES_DIR)),
        keep_trailing_newline=True,
        undefined=jinja2.StrictUndefined,
    )
    template = env.get_template(template_name)
    return template.render(**context)


# ---------- Rich UI ----------


def confirm(prompt: str, *, default: bool = False) -> bool:
    """Interactive yes/no prompt. Returns default when stdin is non-interactive."""
    if not sys.stdin.isatty():
        return default
    suffix = " [Y/n]: " if default else " [y/N]: "
    response = input(prompt + suffix).strip().lower()
    if not response:
        return default
    return response in ("y", "yes")


def status_table(data: dict[str, Any]) -> Table:
    """Build a rich Table for key/value status output."""
    table = Table(show_header=False, box=None)
    table.add_column("Key", style="bold cyan")
    table.add_column("Value")
    for key, value in data.items():
        table.add_row(str(key), str(value))
    return table


def print_url(url: str) -> None:
    """Print URL in a highlighted block."""
    console.print(f"[bold green]URL:[/bold green] [link={url}]{url}[/link]")
